# Generated by Django 4.2 on 2023-05-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_demomodel_email_alter_demomodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demomodel',
            name='career_summary',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='demomodel',
            name='certification',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='demomodel',
            name='declaration',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='demomodel',
            name='eductional_summary',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='demomodel',
            name='personal_details',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='demomodel',
            name='skills',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='demomodel',
            name='work_experience',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
